# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/fedora/Dokumente/Schule/Fachhochschule/Semester_4/Chip_Design/Project_VGA_Controller/code/generate/rom_mem2/rom_mem2/rom_mem2.xci
# IP: The module: 'rom_mem2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fedora/Dokumente/Schule/Fachhochschule/Semester_4/Chip_Design/Project_VGA_Controller/code/generate/rom_mem2/rom_mem2/rom_mem2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_mem2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/fedora/Dokumente/Schule/Fachhochschule/Semester_4/Chip_Design/Project_VGA_Controller/code/generate/rom_mem2/rom_mem2/rom_mem2.xci
# IP: The module: 'rom_mem2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fedora/Dokumente/Schule/Fachhochschule/Semester_4/Chip_Design/Project_VGA_Controller/code/generate/rom_mem2/rom_mem2/rom_mem2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_mem2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
